// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebConsultasMedicas.Data;

#nullable disable

namespace WebConsultasMedicas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418190346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebConsultasMedicas.Models.CitaMedica", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<DateOnly>("FechaCita")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<TimeOnly>("HoraCita")
                        .HasColumnType("time");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoCita")
                        .HasColumnType("int");

                    b.Property<int>("IdHorarioMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("MotivoConsulta")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("IdCita")
                        .HasName("PK_CitaMedica");

                    b.HasIndex("FechaCita")
                        .HasDatabaseName("IX_CitaMedica_FechaCita");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdEstadoCita");

                    b.HasIndex("IdHorarioMedico");

                    b.HasIndex("IdMedico")
                        .HasDatabaseName("IX_CitaMedica_IdMedico");

                    b.HasIndex("IdPaciente")
                        .HasDatabaseName("IX_CitaMedica_IdPaciente");

                    b.HasIndex("IdMedico", "FechaCita", "HoraCita")
                        .IsUnique()
                        .HasDatabaseName("IX_CitaMedicoFechaHora")
                        .HasFilter("[IdEstadoCita] IN (1,2,4)");

                    b.HasIndex("IdPaciente", "FechaCita", "HoraCita")
                        .IsUnique()
                        .HasDatabaseName("IX_CitaPacienteFechaHora")
                        .HasFilter("[IdEstadoCita] IN (1,2,4)");

                    b.ToTable("CitaMedica", (string)null);
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdEspecialidad")
                        .HasName("PK_Especialidad");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Especialidad_Nombre");

                    b.ToTable("Especialidad", (string)null);

                    b.HasData(
                        new
                        {
                            IdEspecialidad = 1,
                            Descripcion = "Atencion general",
                            Estado = true,
                            Nombre = "Medicina General"
                        },
                        new
                        {
                            IdEspecialidad = 2,
                            Descripcion = "Atencion de niños",
                            Estado = true,
                            Nombre = "Pediatria"
                        },
                        new
                        {
                            IdEspecialidad = 3,
                            Descripcion = "Control prenatal y salud materna",
                            Estado = true,
                            Nombre = "Obstetricia"
                        },
                        new
                        {
                            IdEspecialidad = 4,
                            Descripcion = "Atencion dental",
                            Estado = true,
                            Nombre = "Odontologia"
                        });
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.EstadoCita", b =>
                {
                    b.Property<int>("IdEstadoCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCita"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEstadoCita")
                        .HasName("PK_EstadoCita");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_EstadoCita_Nombre");

                    b.ToTable("EstadoCita", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoCita = 1,
                            Nombre = "Programada"
                        },
                        new
                        {
                            IdEstadoCita = 2,
                            Nombre = "Atendida"
                        },
                        new
                        {
                            IdEstadoCita = 3,
                            Nombre = "Cancelada"
                        },
                        new
                        {
                            IdEstadoCita = 4,
                            Nombre = "Reprogramada"
                        },
                        new
                        {
                            IdEstadoCita = 5,
                            Nombre = "No Asistio"
                        });
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.HistorialCita", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoCita")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("UsuarioAccion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdHistorial")
                        .HasName("PK_HistorialCita");

                    b.HasIndex("IdCita");

                    b.HasIndex("IdEstadoCita");

                    b.ToTable("HistorialCita", (string)null);
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.HorarioMedico", b =>
                {
                    b.Property<int>("IdHorarioMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorarioMedico"));

                    b.Property<int>("Cupos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<byte>("DiaSemana")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.HasKey("IdHorarioMedico")
                        .HasName("PK_HorarioMedico");

                    b.HasIndex("IdEspecialidad")
                        .HasDatabaseName("IX_HorarioMedico_IdEspecialidad");

                    b.HasIndex("IdMedico")
                        .HasDatabaseName("IX_HorarioMedico_IdMedico");

                    b.HasIndex("IdTurno");

                    b.ToTable("HorarioMedico", null, t =>
                        {
                            t.HasCheckConstraint("CK_HorarioMedico_Cupos", "[Cupos] > 0");

                            t.HasCheckConstraint("CK_HorarioMedico_DiaSemana", "[DiaSemana] BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Medico", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedico"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CMP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdMedico")
                        .HasName("PK_Medico");

                    b.HasIndex("CMP")
                        .IsUnique()
                        .HasDatabaseName("UQ_Medico_CMP");

                    b.ToTable("Medico", (string)null);
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.MedicoEspecialidad", b =>
                {
                    b.Property<int>("IdMedicoEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicoEspecialidad"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.HasKey("IdMedicoEspecialidad")
                        .HasName("PK_MedicoEspecialidad");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdMedico", "IdEspecialidad")
                        .IsUnique()
                        .HasDatabaseName("UQ_MedicoEspecialidad");

                    b.ToTable("MedicoEspecialidad", (string)null);
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroSIS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdPaciente")
                        .HasName("PK_Paciente");

                    b.HasIndex("DNI")
                        .IsUnique()
                        .HasDatabaseName("UQ_Paciente_DNI");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("UQ_Paciente_IdUsuario");

                    b.HasIndex("NumeroSIS")
                        .IsUnique()
                        .HasDatabaseName("UQ_Paciente_NumeroSIS");

                    b.ToTable("Paciente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Paciente_Sexo", "[Sexo] IN ('M','F')");
                        });
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK_Rol");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Rol_Nombre");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Estado = true,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Estado = true,
                            Nombre = "Paciente"
                        });
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTurno")
                        .HasName("PK_Turno");

                    b.ToTable("Turno", (string)null);

                    b.HasData(
                        new
                        {
                            IdTurno = 1,
                            Estado = true,
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            Nombre = "Mañana"
                        },
                        new
                        {
                            IdTurno = 2,
                            Estado = true,
                            HoraFin = new TimeOnly(18, 0, 0),
                            HoraInicio = new TimeOnly(14, 0, 0),
                            Nombre = "Tarde"
                        });
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario")
                        .HasName("PK_Usuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_Correo");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.CitaMedica", b =>
                {
                    b.HasOne("WebConsultasMedicas.Models.Especialidad", "Especialidad")
                        .WithMany("Citas")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CitaMedica_Especialidad");

                    b.HasOne("WebConsultasMedicas.Models.EstadoCita", "EstadoCita")
                        .WithMany("Citas")
                        .HasForeignKey("IdEstadoCita")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CitaMedica_EstadoCita");

                    b.HasOne("WebConsultasMedicas.Models.HorarioMedico", "HorarioMedico")
                        .WithMany("Citas")
                        .HasForeignKey("IdHorarioMedico")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CitaMedica_HorarioMedico");

                    b.HasOne("WebConsultasMedicas.Models.Medico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CitaMedica_Medico");

                    b.HasOne("WebConsultasMedicas.Models.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CitaMedica_Paciente");

                    b.Navigation("Especialidad");

                    b.Navigation("EstadoCita");

                    b.Navigation("HorarioMedico");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.HistorialCita", b =>
                {
                    b.HasOne("WebConsultasMedicas.Models.CitaMedica", "CitaMedica")
                        .WithMany("Historial")
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_HistorialCita_CitaMedica");

                    b.HasOne("WebConsultasMedicas.Models.EstadoCita", "EstadoCita")
                        .WithMany("Historiales")
                        .HasForeignKey("IdEstadoCita")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_HistorialCita_EstadoCita");

                    b.Navigation("CitaMedica");

                    b.Navigation("EstadoCita");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.HorarioMedico", b =>
                {
                    b.HasOne("WebConsultasMedicas.Models.Especialidad", "Especialidad")
                        .WithMany("Horarios")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_HorarioMedico_Especialidad");

                    b.HasOne("WebConsultasMedicas.Models.Medico", "Medico")
                        .WithMany("Horarios")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_HorarioMedico_Medico");

                    b.HasOne("WebConsultasMedicas.Models.Turno", "Turno")
                        .WithMany("Horarios")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_HorarioMedico_Turno");

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.MedicoEspecialidad", b =>
                {
                    b.HasOne("WebConsultasMedicas.Models.Especialidad", "Especialidad")
                        .WithMany("MedicosEspecialidades")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MedicoEspecialidad_Especialidad");

                    b.HasOne("WebConsultasMedicas.Models.Medico", "Medico")
                        .WithMany("MedicosEspecialidades")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MedicoEspecialidad_Medico");

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Paciente", b =>
                {
                    b.HasOne("WebConsultasMedicas.Models.Usuario", "Usuario")
                        .WithOne("Paciente")
                        .HasForeignKey("WebConsultasMedicas.Models.Paciente", "IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Paciente_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Usuario", b =>
                {
                    b.HasOne("WebConsultasMedicas.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.CitaMedica", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Especialidad", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Horarios");

                    b.Navigation("MedicosEspecialidades");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.EstadoCita", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.HorarioMedico", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Medico", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Horarios");

                    b.Navigation("MedicosEspecialidades");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Paciente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Turno", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("WebConsultasMedicas.Models.Usuario", b =>
                {
                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
